language: php

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - PACKAGE_VERSION=""
    - PHPUNIT_FLAGS="-v"
    - PHPUNIT_VERSION=""
    - SIMPLE_PHPUNIT_INSTALL="true"
    - SYMFONY_SHOW_VERSION="true"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
  fast_finish: true
  include:
      # Minimum supported dependencies with the latest and oldest PHP version
#  @php version
#    - php: 5.6
#      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0" SIMPLE_PHPUNIT_INSTALL=''
# @The each() function is deprecated. This message will be suppressed on further calls
#    - php: 7.2
#      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0" SIMPLE_PHPUNIT_INSTALL=''
#    - php: 7.3
#      env: SYMFONY_VERSION='4.*' COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0" PHPUNIT_VERSION='^9.1' SIMPLE_PHPUNIT_INSTALL='' PACKAGE_VERSION=^2.
# @No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
#    - php: 7.4
#      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

#      # Test the latest stable release
# @php version
#    - php: 5.6
#      env: COMPOSER_FLAGS="--prefer-lowest" SIMPLE_PHPUNIT_INSTALL=''

# @deprecate
#    - php: 7.2

      # Test LTS versions. This makes sure we do not use Symfony packages with version greater
      # than 2 or 3 respectively. Read more at https://github.com/symfony/lts
    - php: 5.6
      env: DEPENDENCIES="symfony/lts:^2" PACKAGE_VERSION=^2.1.2
    - php: 5.6
      env: DEPENDENCIES="symfony/lts:^3" PACKAGE_VERSION=^2.1.2
# @deprecate
    - php: 7.2
      env: DEPENDENCIES="symfony/lts:^2" PACKAGE_VERSION=^2.1.2 SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
# @deprecate
    - php: 7.2
      env: DEPENDENCIES="symfony/lts:^3" PACKAGE_VERSION=^2.1.2 SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
# @conflict
#    - php: 7.4
#      env: DEPENDENCIES="symfony/lts:^2" PACKAGE_VERSION=^2.
# @deprecate
    - php: 7.4
      env: DEPENDENCIES="symfony/lts:^3" PACKAGE_VERSION=^2.1.2 SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

    - php: 7.4
      env: SYMFONY_VERSION='5.0.*' SYMFONY_DEPRECATIONS_HELPER=weak PACKAGE_VERSION=^2.1.3
    - php: 8.0
      env: SYMFONY_VERSION='5.0.*' SYMFONY_DEPRECATIONS_HELPER=weak PACKAGE_VERSION=^2.1.3

    - php: 7.4
      env: SYMFONY_VERSION='5.1.*' SYMFONY_DEPRECATIONS_HELPER=weak PACKAGE_VERSION=^2.1.3
    - php: 8.0
      env: SYMFONY_VERSION='5.1.*' SYMFONY_DEPRECATIONS_HELPER=weak PACKAGE_VERSION=^2.1.3

    - php: 7.4
      env: SYMFONY_VERSION='5.2.*' SYMFONY_DEPRECATIONS_HELPER=weak PACKAGE_VERSION=^2.1.3
    - php: 8.0
      env: SYMFONY_VERSION='5.2.*' SYMFONY_DEPRECATIONS_HELPER=weak PACKAGE_VERSION=^2.1.3

    # Latest commit to master
    - php: 7.4
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text" SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 8.0
      env: STABILITY="dev"  SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

  allow_failures:
      # Dev-master is allowed to fail.
    - env: STABILITY="dev"

before_install:
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if ! [ -z "$PACKAGE_VERSION" ]; then git pull --tags; export TAG=$(git tag 2> /dev/null | grep $(git tag | sed -e 's/^.//' | grep "$PACKAGE_VERSION" | tail -n1)); fi;
  - echo ${TAG}
  - if ! [ -z "$TAG" ]; then git checkout tags/${TAG} -b ${TAG}; fi;
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
  - if ! [ -z "$PHPUNIT_VERSION" ]; then composer --no-update require --dev phpunit/phpunit ${PHPUNIT_VERSION}; fi;
  - if ! [ -z "$SYMFONY_VERSION" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;

install:
  - echo ${COMPOSER_FLAGS}
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - echo ${SIMPLE_PHPUNIT_INSTALL}
  - if ! [ -z "$SYMFONY_SHOW_VERSION" ]; then cat vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php | grep -w 'VERSION' | awk '{print $4}' | sed "s/[;']//g"; fi;
  - if ! [ -z "$SIMPLE_PHPUNIT_INSTALL" ]; then ./vendor/bin/simple-phpunit install; fi;

script:
  - composer validate --strict --no-check-lock
  # simple-phpunit is the PHPUnit wrapper provided by the PHPUnit Bridge component and
  # it helps with testing legacy code and deprecations (composer require symfony/phpunit-bridge)
  #- ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS
  - ./vendor/bin/phpunit $PHPUNIT_FLAGS
